/* BUS 440: practice questions written from the 2025/26 materials, following the
   course-outline allocation: 1 Inventory · 2 Management & theories · 3 TQM ·
   4 Leadership, skills & organisations · 5 Quality control & SPC · 6 Project management. */
BANKS["bus-new"] = {
  id: "bus-new", course: "BUS", kind: "new",
  title: "BUS 440 Practice",
  subtitle: "Written from the 2025/26 lectures, decks and handwritten notes",
  meta: "Six syllabus blocks, following the course outline",
  q: [
/* ── 1 · INVENTORY MANAGEMENT ── */
{t:"Inventory",s:"Block 1 · Adekoya",q:"Inventory resources are classified into three. They include all except",o:["Physical resources","Human resources","Financial resources","Intangible resources"],a:3,
 w:"Physical resources (raw materials, semi-finished and finished goods, spare parts), human resources (unused labour or manpower) and financial resources (working capital)."},
{t:"Inventory",s:"Block 1",q:"A system in which orders are placed at regular intervals of time, with the quantity varying according to the inventory on hand at review, is the",o:["Periodic Review System","Fixed Order Quantity System","Optional Replenishment System","Two-bin system"],a:0,
 w:"Contrast the Fixed Order Quantity System, where the level is monitored continuously and a fixed quantity is ordered once it drops to a set point."},
{t:"Inventory",s:"Block 1",q:"A periodic review system with a minimum order quantity restriction, so that no order is placed if the calculated quantity falls below the minimum, is the",o:["Periodic Review System","Fixed Order Quantity System","Optional Replenishment System","ABC system"],a:2,
 w:"Its purpose is to avoid the cost of placing many small, uneconomic orders."},
{t:"Inventory",s:"Block 1",q:"In the Fixed Order Quantity System, variation in demand is accommodated by changing",o:["the order quantity","the time between orders","the unit price","the safety stock only"],a:1,
 w:"The quantity is fixed by definition, so it is the interval that flexes. In the periodic system the reverse is true: the interval is fixed and the quantity flexes."},
{t:"Inventory",s:"Block 1",q:"Which of these is NOT a component of total inventory cost?",o:["Purchase cost","Ordering cost","Carrying cost","Shortage cost","Marketing cost"],a:4,
 w:"$\\mathrm{TC} = P_c + O_c + H_o + S_o = (\\text{price} \\times \\text{qty}) + \\frac{D}{Q}O + \\frac{Q}{2}H$, plus shortage cost where applicable.",
 calc:"\\mathrm{TC} = PQ + \\frac{D}{Q}O + \\frac{Q}{2}H"},
{t:"Inventory",s:"Block 1",q:"As the quantity ordered rises, ordering cost per year",o:["rises","falls","stays constant","rises then falls"],a:1,
 w:"Bigger orders mean fewer orders per year, so the ordering cost curve slopes downward while the holding cost curve slopes upward. EOQ sits where their sum is lowest."},
{t:"Inventory",s:"Block 1",q:"Loss of sales, goodwill and customers are examples of",o:["ordering cost","holding cost","stockout or shortage cost","set-up cost"],a:2,
 w:"Shortage cost is what running out of stock costs you, and it is the reason safety stock is carried at all."},
{t:"Inventory",s:"Block 1",q:"Costs incurred in cleaning, adjusting and adapting machines in readiness for the next production run are",o:["ordering costs","set-up costs","holding costs","purchase costs"],a:1,
 w:"Set-up cost is the producer’s analogue of the buyer’s ordering cost, which is why it drives the Economic Batch Quantity rather than the EOQ."},
{t:"Inventory",s:"Block 1",q:"The EOQ model was formulated in 1915 by",o:["F. W. Taylor","F. W. Harris","Henri Fayol","Max Weber","W. E. Deming"],a:1,
 w:"Ford W. Harris. Do not confuse him with F. W. Taylor, the father of scientific management."},
{t:"Inventory",s:"Block 1",q:"Which is NOT an assumption of the EOQ model?",o:["Demand is known and constant","Lead time is zero","Backorder is allowed","No constraints on order size","Unit price of items is fixed"],a:2,
 w:"The six assumptions are: demand known and constant; zero lead time; backorder NOT allowed; no constraints on order size; fixed order cost; fixed unit price."},
{t:"Inventory",s:"Block 1",q:"In a deterministic inventory model, as opposed to a stochastic model,",o:["price and demand vary","demand and lead time are known and constant","only holding cost varies","no costs are considered"],a:1,
 w:"In stochastic (probabilistic) models everything varies: price, demand, holding and ordering costs."},
{t:"Inventory · EOQ",s:"Block 1",q:"Annual demand is 600,000 units, the cost per order is ₦20 and carrying cost is ₦0.70 per unit. What is the EOQ?",o:["5,856 units","1,789 units","2,449 units","4,286 units"],a:0,
 w:"$\\mathrm{EOQ} = \\sqrt{\\frac{2DO}{H}} = \\sqrt{\\frac{2 \\times 600{,}000 \\times 20}{0.70}} = \\sqrt{34{,}285{,}714} = 5{,}855.4$, rounded up to 5,856 units.",
 calc:"\\mathrm{EOQ} = \\sqrt{\\frac{2 \\times 600{,}000 \\times 20}{0.70}} = 5{,}855.4 \\to 5{,}856"},
{t:"Inventory · EOQ",s:"Block 1",q:"Using the same figures ($D = 600{,}000$, $\\mathrm{EOQ} = 5{,}856$), how many times should the company order per year?",o:["103 times","52 times","12 times","205 times"],a:0,
 w:"Number of orders $= \\frac{D}{\\mathrm{EOQ}} = \\frac{600{,}000}{5{,}856} = 102.46$, rounded up to 103.",
 calc:"N = \\frac{D}{\\mathrm{EOQ}} = \\frac{600{,}000}{5{,}856} = 102.46 \\to 103"},
{t:"Inventory · EOQ",s:"Block 1",q:"Annual demand is 600,000 units, order cost ₦20, unit price ₦50 and carrying cost is 15% of unit price. What is the EOQ?",o:["5,856 units","1,789 units","3,464 units","1,265 units"],a:1,
 w:"$H = 15\\% \\times ₦50 = ₦7.50$. Then $\\mathrm{EOQ} = \\sqrt{\\frac{2 \\times 600{,}000 \\times 20}{7.5}} = \\sqrt{3{,}200{,}000} = 1{,}788.8$, rounded up to 1,789 units.",
 calc:"H = 0.15 \\times 50 = 7.5 \\qquad \\mathrm{EOQ} = \\sqrt{\\frac{2 \\times 600{,}000 \\times 20}{7.5}} = 1{,}789"},
{t:"Inventory · EOQ",s:"Block 1",q:"With EOQ = 5,856 units and annual demand of 600,000 units, the ordering interval on a 360-day year is approximately",o:["4 days","12 days","30 days","2 days"],a:0,
 w:"Interval $= \\frac{\\mathrm{EOQ}}{D} \\times 360 = \\frac{5{,}856}{600{,}000} \\times 360 = 3.5$ days, taken as 4 days.",
 calc:"t = \\frac{Q}{D} \\times 360 = \\frac{5{,}856}{600{,}000} \\times 360 = 3.5 \\to 4\\text{ days}"},
{t:"Inventory",s:"Block 1",q:"Which is NOT a factor involved in inventory problem analysis?",o:["Replenishment lead time","Length of the planning period","Customer service level","The advertising budget","Constraints on the inventory system"],a:3,
 w:"The listed factors are relevant inventory costs, demand, replenishment lead time, planning period length, system constraints (space, budget, cash) and customer service level."},
/* ── 2 · MANAGEMENT: EVOLUTION, DEFINITION, FUNCTIONS ── */
{t:"Management",s:"Block 2 · Edegwa",q:"Who defined management as forecasting, planning, organising, commanding, coordinating and controlling?",o:["Henri Fayol","Mary Parker Follett","Peter Drucker","Harold Koontz","George Terry"],a:0,
 w:"Fayol (1916) framed management as a continuous process. Follett called it the art of getting things done through people; Drucker called it the organ that converts resources into productive performance."},
{t:"Management",s:"Block 2",q:"“Management is the organ of institutions that converts resources into productive performance” is the definition of",o:["Henri Fayol","Peter Drucker","Elton Mayo","Max Weber"],a:1,
 w:"Drucker (1974) views management as a productivity tool, a useful contrast with Koontz and O’Donnell, who stress designing an environment for group achievement."},
{t:"Management",s:"Block 2",q:"The five functions of management are",o:["planning, organizing, staffing, directing and controlling","forecasting, budgeting, hiring, firing and auditing","planning, marketing, selling, delivering and invoicing","initiating, planning, executing, monitoring and closing"],a:0,
 w:"The last option is the project life cycle, not the functions of management, a distinction the examiner has tested before."},
{t:"Management",s:"Block 2",q:"Which of these is NOT a listed step in the controlling function?",o:["Set performance standards","Measure actual performance","Recruit and train employees","Compare results with standards","Take corrective action"],a:2,
 w:"Recruitment and training belong to staffing. Controlling measures performance against plan and feeds the result back into future planning."},
{t:"Management",s:"Block 2",q:"Assigning civil, electrical and mechanical engineers to different work packages on a construction project is an example of",o:["planning","organizing","staffing","controlling"],a:1,
 w:"Organizing arranges resources and assigns responsibilities: designing structures, allocating tasks, delegating authority and coordinating departments."},
{t:"Management",s:"Block 2",q:"Frederick Winslow Taylor is known as the father of",o:["administrative management","scientific management","bureaucratic management","human relations"],a:1,
 w:"Fayol is the father of administrative management, Weber of bureaucratic theory, and Mayo is associated with human relations."},
{t:"Management",s:"Block 2",q:"Which is NOT one of Taylor’s principles of scientific management?",o:["Science instead of rule of thumb","Scientific selection of workers","Scientific training","Cooperation between workers and managers","Maximum span of control"],a:4,
 w:"The fifth principle is equal division of work and responsibility. Span of control is one of Fayol’s concerns, not Taylor’s."},
{t:"Management",s:"Block 2",q:"The main criticism of scientific management is that it",o:["was too expensive to implement","treated workers like machines and ignored social needs","produced no measurable gains","could not be applied to manufacturing"],a:1,
 w:"That neglect of the human side is exactly what the neo-classical or behavioural school arose to correct."},
{t:"Management",s:"Block 2",q:"Which of these is NOT among Fayol’s 14 principles of management?",o:["Unity of command","Scalar chain","Esprit de corps","Espousal of change","Equity"],a:3,
 w:"The 14 are division of work, authority and responsibility, discipline, unity of command, unity of direction, subordination of individual interest, remuneration, centralization, scalar chain, order, equity, stability of tenure, initiative and esprit de corps."},
{t:"Management",s:"Block 2",q:"Max Weber’s bureaucratic theory is characterised by all except",o:["formal hierarchy","merit-based recruitment","impersonal relationships","personal loyalty to the leader","written documentation"],a:3,
 w:"Weber’s point was that organisations should be governed by rational rules rather than personal relationships. Its criticisms are rigidity, slow decisions, paperwork and resistance to innovation."},
{t:"Management",s:"Block 2",q:"The Hawthorne Studies (1924–1932) at the Western Electric Company are associated with",o:["Elton Mayo","Abraham Maslow","Douglas McGregor","Fred Fiedler"],a:0,
 w:"The findings (that employees are motivated by recognition, that informal groups influence behaviour, that social factors matter) founded the human relations school."},
{t:"Management",s:"Block 2",q:"Maslow, McGregor, Herzberg and Argyris are the main contributors to",o:["scientific management","behavioural science theory","systems theory","contingency theory"],a:1,
 w:"They studied motivation, leadership, personality, learning, organisational culture and employee satisfaction."},
{t:"Management",s:"Block 2",q:"Systems theory, associated with Ludwig von Bertalanffy, describes an organisation as",o:["a machine to be optimised","interrelated and interdependent parts working towards common goals","a hierarchy of rational rules","a market of individual bargains"],a:1,
 w:"Its components are inputs, transformation process, outputs, feedback and environment. In an engineering project, failure in one subsystem affects the whole."},
{t:"Management",s:"Block 2",q:"“There is no one best way to manage” is the central proposition of",o:["bureaucratic theory","contingency theory","scientific management","total quality management"],a:1,
 w:"Fiedler, Lawrence and Lorsch are the contributors. Decisions depend on organisational size, technology, environment, employees and goals."},
{t:"Management",s:"Block 2",q:"Operations research, linear programming, simulation, queuing theory and decision analysis belong to",o:["administrative theory","quantitative (management science) theory","human relations theory","agile management"],a:1,
 w:"Its strength is analytical accuracy; its weakness is that it may overlook human factors."},
{t:"Management",s:"Block 2",q:"Which is NOT one of the seven types of waste identified in Lean Management?",o:["Overproduction","Waiting time","Excess inventory","Excess documentation","Overprocessing"],a:3,
 w:"The seven are overproduction, waiting time, excess inventory, defects, unnecessary transportation, excess motion and overprocessing."},
{t:"Management",s:"Block 2",q:"Agile management is characterised by flexibility, collaboration and iterative development. Its main weakness is that it is",o:["too expensive","less suitable for highly rigid environments","impossible to measure","incompatible with software engineering"],a:1,
 w:"Its strengths are innovation and speed, which is why it dominates software engineering, product development and R&D."},
{t:"Management",s:"Block 2",q:"Management is regarded as an art because it involves all except",o:["practical application of knowledge","personal skills and creativity","experience","universal principles tested by experiment"],a:3,
 w:"Testable, universal principles developed by observation and experimentation are the marks of management as a science."},
{t:"Management",s:"Block 2",q:"Which pairing correctly describes management as an art versus as a science?",o:["Art is objective; science is subjective","Art is learned through experience; science is learned through education and research","Art focuses on facts; science focuses on judgment","Art is concerned with theory; science with application"],a:1,
 w:"Art rests on practical skill, creativity and judgment; science on systematic knowledge, analysis and evidence. Every other option reverses the pair."},
{t:"Management",s:"Block 2",q:"The modern position on the art-versus-science debate is that",o:["management is purely a science","management is purely an art","management is both: science provides the knowledge, art the ability to apply it","the debate has no practical consequence"],a:2,
 w:"A project manager needs CPM, PERT, risk analysis and forecasting, and also leadership, negotiation, conflict resolution and emotional intelligence."},
{t:"Management",s:"Block 2",q:"Which best distinguishes administration from management?",o:["Administration implements policies; management formulates them","Administration formulates policies and is strategic; management implements them and is operational","Both are identical in every respect","Administration operates at the lower level; management at the top"],a:1,
 w:"Administration is concerned with what and why and directs managers; management is concerned with how and supervises employees. Administration emphasises effectiveness; management, efficiency."},
{t:"Management",s:"Block 2",q:"Theo Haimann and E. F. L. Brech both define administration in terms of",o:["supervising employees","determining objectives and major policies","measuring performance against standards","recruiting and training staff"],a:1,
 w:"Haimann: the overall determination of policies, setting of major objectives and laying down of broad programmes. Brech: concerned with determining the objectives and major policies of an organization. Both point to the top level."},
/* ── 3 · TOTAL QUALITY MANAGEMENT ── */
{t:"TQM",s:"Block 3 · Oyenuga",q:"TQM is summarised in the maxim",o:["“Do the right things, right the first time, every time”","“Let the buyer beware”","“No one best way”","“Inspect at the end of the line”"],a:0,
 w:"Total (the whole) + Quality (degree of excellence) + Management (getting things done through people)."},
{t:"TQM",s:"Block 3",q:"Which is NOT listed among the core principles of TQM?",o:["Customer focus","Continuous improvement","Employee involvement","Departmental independence","Effective communication"],a:3,
 w:"TQM is explicitly an integrated system with a process approach; departments working in isolation is the opposite of what it asks for."},
{t:"TQM",s:"Block 3",q:"The dimension of TQM concerned with training, empowerment and participation is",o:["leadership commitment","customer satisfaction","employee involvement","process management"],a:2,
 w:"The six dimensions are leadership commitment, customer satisfaction, employee involvement, process management, continuous improvement (Kaizen) and fact-based decision-making."},
{t:"TQM",s:"Block 3",q:"Which TQM tool is used for visualising process steps?",o:["Pareto chart","Fishbone diagram","Flow chart","Check sheet"],a:2,
 w:"A flowchart maps the sequence of steps and the relationship between inputs, activities, decision points and outputs."},
{t:"TQM",s:"Block 3",q:"All of the following are listed as obstacles to implementing TQM except",o:["Lack of management commitment","Resistance to change","Insufficient training","Excessive employee engagement","Short-term focus over long-term goals"],a:3,
 w:"Poor employee engagement is an obstacle; excessive engagement is not a recognised problem. The other obstacles are inadequate resources and misunderstanding of TQM principles."},
{t:"TQM",s:"Block 3",q:"Which is NOT a listed strategy for overcoming TQM barriers?",o:["Secure top management support","Provide continuous training and education","Reduce communication to avoid confusion","Align TQM with organisational goals","Recognise and reward quality improvements"],a:2,
 w:"Encouraging open communication is the actual strategy, the reverse of what this option states."},
{t:"TQM",s:"Block 3",q:"ISO 9000 and ISO 9001 differ in that",o:["ISO 9000 covers fundamentals and ISO 9001 covers requirements","ISO 9000 is Nigerian and ISO 9001 is international","ISO 9000 applies to services and ISO 9001 to goods","they are identical"],a:0,
 w:"ISO 9000 sets out the fundamentals and vocabulary of quality management systems; ISO 9001 states the requirements against which an organisation is certified."},
{t:"TQM",s:"Block 3",q:"ISO 14000 relates to",o:["quality management systems","environmental management","information security","food safety"],a:1,
 w:"Also listed among other quality systems are Six Sigma, Lean management, the Baldrige Performance Excellence Program, NAFDAC and the NUC."},
{t:"TQM",s:"Block 3",q:"A restaurant that regularly gathers feedback through surveys and comment cards is practising which TQM principle?",o:["Customer focus","Supplier relationship management","Process approach","Factual decision making"],a:0,
 w:"The two overlap (the survey generates the data) but the principle being illustrated is understanding and meeting customer needs."},
{t:"TQM",s:"Block 3",q:"An automobile manufacturer that sets quality standards for its parts suppliers and audits them regularly is practising",o:["employee involvement","supplier relationship management","strategic approach","continuous training"],a:1,
 w:"TQM extends past the organisation’s own walls: the quality of inputs limits the quality of outputs."},
{t:"TQM",s:"Block 3",q:"In the lead-time example, ‘lead time’ means",o:["the time a manager leads a project","the time from order processing through preparation and transportation to delivery","the time taken to train an employee","the interval between two audits"],a:1,
 w:"Mapping the fulfilment process to find bottlenecks is how the logistics company in the notes reduced it."},
{t:"TQM",s:"Block 3",q:"Which is NOT listed as a benefit of TQM?",o:["Higher customer satisfaction","Increased efficiency and productivity","Guaranteed elimination of all competition","Better employee morale","Cost reduction and fewer errors"],a:2,
 w:"TQM enhances competitive advantage; it does not remove competitors."},
/* ── 4 · LEADERSHIP, SKILLS, ORGANISATIONS, COMMUNICATION ── */
{t:"Leadership",s:"Block 4 · Ehiorobo",q:"The clearest distinction between leadership and management is that",o:["management sets direction and drives change; leadership plans and controls","leadership sets direction, motivates and drives change; management plans, organizes, budgets and controls","they are the same activity under different names","leadership applies only to top management"],a:1,
 w:"Effective managers combine both. The examiner has previously tested the point by asking whether leadership is ‘the same as’ management: it is an influence process, not management."},
{t:"Leadership",s:"Block 4",q:"Which is NOT among the five essential leadership qualities listed?",o:["Integrity and accountability","Effective communication","Vision and purpose","Financial independence","Adaptability and resilience"],a:3,
 w:"The fifth is empathy and emotional intelligence."},
{t:"Leadership",s:"Block 4",q:"The five pillars of trust in leadership are integrity, competence, consistency, openness and",o:["ambition","connection or empathy","seniority","charisma"],a:1,
 w:"The parallel ‘five Cs’ formulation gives competence, communication, commitment, caring and character."},
{t:"Leadership",s:"Block 4",q:"Which is listed as an impact of a high-trust environment?",o:["Increased performance, loyalty and retention, and reduced risk","Higher staff turnover","Slower decision-making","Greater need for supervision"],a:0,
 w:"Trust lets teams take risks, support each other and adapt to change."},
{t:"Communication",s:"Block 4",q:"The 7Cs of communication are clarity, conciseness, correctness, completeness, courtesy, concreteness and",o:["confidence","consideration","conformity","control"],a:1,
 w:"All seven begin with C: clarity, conciseness, correctness, completeness, courtesy, concreteness and consideration. Together they form the foundation for expressing ideas efficiently and professionally."},
{t:"Communication",s:"Block 4",q:"The three rules that govern good communication include all except",o:["Be clear in your own mind about what you want to communicate","Deliver the message succinctly","Ensure the message has been clearly and correctly understood","Repeat the message at least three times"],a:3,
 w:"Good communication means saying what you mean and fully comprehending any feedback."},
{t:"Communication",s:"Block 4",q:"Gestures, facial expressions, tone of voice, silence, posture, absence and presence are classified as",o:["written words","spoken words","symbolic gestures","visual images"],a:2,
 w:"Visual images are photographs, charts, graphs, logos and films; multimedia combines them."},
{t:"Communication",s:"Block 4",q:"Which is NOT among the rules given for delivering negative feedback?",o:["Show an understanding of exactly what went wrong, and why","Draw out ways in which poor performance can improve","Use questions rather than assertions","Deliver it publicly so others can learn","Be objective and avoid being emotional or personal"],a:3,
 w:"The aim of the rules is to avoid antagonism, and public criticism is the surest way to provoke it."},
{t:"Managerial roles",s:"Block 4 · Mintzberg",q:"Mintzberg grouped managerial roles into three categories:",o:["planning, organizing and controlling","interpersonal, informational and decision-making","technical, human and conceptual","top, middle and low level"],a:1,
 w:"Technical, human and conceptual are Katz’s skills; top, middle and low are the levels of management. Keep the three schemes apart."},
{t:"Managerial roles",s:"Block 4 · Mintzberg",q:"A manager who receives visitors, speaks at functions and signs legal documents on behalf of the company is acting as a",o:["figurehead","leader","liaison officer","disseminator"],a:0,
 w:"All three are interpersonal roles: figurehead (ceremonial and symbolic), leader (motivating by example) and liaison (maintaining the outside network)."},
{t:"Managerial roles",s:"Block 4 · Mintzberg",q:"A manager who reads newspapers, reports and periodicals to track outside developments that could affect the company is acting as a",o:["monitor","disseminator","spokesman","negotiator"],a:0,
 w:"The informational roles are monitor (collects), disseminator (passes information down and across) and spokesman (represents the unit outward)."},
{t:"Managerial roles",s:"Block 4 · Mintzberg",q:"Settling differences among employees and conflicts between staff and top management is the role of the manager as",o:["entrepreneur","disturbance handler","resource allocator","negotiator"],a:1,
 w:"The four decision-making roles are entrepreneur (seeks new ideas), disturbance handler, resource allocator (prepares budgets) and negotiator (contracts, prices, unions)."},
{t:"Managerial levels",s:"Block 4",q:"Frontline or operational managers who supervise operations and link management with non-management personnel are at",o:["low level management","middle level management","top level management","board level"],a:0,
 w:"Middle managers are the tactical managers who translate general goals into specific objectives; top managers are the strategic managers concerned with survival, growth and the external environment."},
{t:"Managerial levels",s:"Block 4",q:"Middle level managers are described as the linchpins of internal communication because they",o:["hold the largest budgets","interpret top management priorities downward and channel information upward","have the most technical skill","report directly to shareholders"],a:1,
 w:"They also supply the creative ideas, operating skills and practical problem-solving that keep the organisation working."},
{t:"Managerial skills",s:"Block 4 · Katz",q:"Robert L. Katz (1974) identified which three basic managerial skills?",o:["Technical, human and conceptual","Planning, organizing and controlling","Interpersonal, informational and decisional","Strategic, tactical and operational"],a:0,
 w:"Skills are specific abilities arising from knowledge, information, practice and aptitude. Option (b) gives the functions of management and option (c) Mintzberg’s roles, three separate schemes the examiner likes to mix."},
{t:"Managerial skills",s:"Block 4 · Katz",q:"The ability to have an overview of the entire organization, how it works and how the parts relate, is",o:["technical skill","human relation skill","conceptual skill","negotiation skill"],a:2,
 w:"Technical skill is the ability to use the tools and techniques of a specialised field; human skill is working with, understanding and motivating people."},
{t:"Managerial skills",s:"Block 4 · Katz",q:"Which statement about the relative importance of managerial skills is correct?",o:["Technical skill grows more important as one moves up the hierarchy","Conceptual skill grows more important as one moves up, while technical skill becomes less so","Human skill matters only at the top level","Conceptual skill matters only at the lowest level"],a:1,
 w:"Human skill is very important at every level, because management is simply getting things done through other people."},
{t:"Organisations",s:"Block 4",q:"Which form of organisation is also known as the scalar or military type?",o:["Line organisation","Functional organisation","Line and staff organisation","Informal organisation"],a:0,
 w:"It is characterised by direct lines of authority flowing top to bottom and responsibility flowing back, with a clear superior-subordinate relationship."},
{t:"Organisations",s:"Block 4",q:"Which is NOT an advantage of the line organisation?",o:["Simple to establish","Fixed responsibility","Quick decision","Specialisation in all managerial functions","Discipline from unity of command"],a:3,
 w:"Lack of specialisation is one of its disadvantages: the executive may not be expert in every aspect of managerial activity. Others are overload and lack of initiative."},
{t:"Organisations",s:"Block 4",q:"The chief demerit of the functional organisation is",o:["lack of specialisation","conflict of authority, since a subordinate reports to more than one boss","excessive simplicity","absence of departments"],a:1,
 w:"It violates unity of command. It is also expensive because of the multiplicity of experts, and coordination is slow."},
{t:"Organisations",s:"Block 4",q:"In the line and staff organisation, the relationship between the two is that",o:["staff enforce decisions and line members advise","staff members are thinkers who prepare plans; line officers are doers who execute them","staff members outrank line officers","line officers have no authority"],a:1,
 w:"The staff has power to recommend, not to enforce. Its demerits are line-staff conflict, ambiguity over authority, lack of accountability for wrong advice, and expense."},
{t:"Organisations",s:"Block 4",q:"An informal organisation is best described as",o:["a registered subsidiary","the grouping of people emerging unofficially and not designated as part of the organisation","a temporary project team appointed by management","a trade union"],a:1,
 w:"It exists to satisfy human needs the formal structure does not, and often appears as cliques or sub-groups within it."},
{t:"Organisations",s:"Block 4",q:"Which is NOT listed as a function of the informal organisation?",o:["Providing a grapevine for speedy communication","Perpetuating the culture of a group","Enabling members to acquire status","Setting the organisation’s official pay scales"],a:3,
 w:"Informal groups may set their own norms (agreeing on a 20-minute tea break where management allowed 15) but they do not set official terms."},
{t:"Organisations",s:"Block 4",q:"Which is a listed limitation of the informal organisation?",o:["It brings cohesiveness to members","It is a breeding ground for future leaders","Information could be negatively filtered and multiple leadership may arise","It improves worker productivity"],a:2,
 w:"It may also lead to violation of official rules and lack of uniformity in applying official relationships. Management is advised to direct rather than suppress it."},
/* ── 5 · QUALITY CONTROL & SPC ── */
{t:"Quality control",s:"Block 5 · Olonade",q:"Quality control is best defined as",o:["the set of procedures used to assess the suitability, effectiveness and conditions of products and services","the marketing of high-quality products","the recruitment of skilled technicians","the pricing of goods according to quality"],a:0,
 w:"It is a systematic control of the factors affecting product quality: materials, tools, machines, type of labour and working conditions."},
{t:"Quality control",s:"Block 5",q:"The goal of quality control is to prevent, identify and control errors or defects",o:["after the product reaches the customer","ideally during production, before the product reaches the customer or the next stage","only at the design stage","only through customer complaints"],a:1,
 w:"Hence the series of checks: design stage, lab testing and simulations, and pre-production material inspection."},
{t:"Quality control",s:"Block 5",q:"Which is NOT among the listed objectives of quality control?",o:["To improve the company’s income by making production more acceptable to customers","To reduce cost through reduction of losses due to defects","To achieve interchangeability in large scale production","To increase the selling price of every product","To check variation during manufacturing"],a:3,
 w:"An objective is in fact to produce optimal quality at reduced price."},
{t:"Quality control",s:"Block 5",q:"Deciding how defective parts are disposed of (whether entirely scrapped or reworked) is which step in quality control?",o:["Formulating quality policy","Selecting the inspection plan","Deciding on salvage method","Detecting deviations"],a:2,
 w:"The nine steps run from formulating quality policy through to developing procedures for good vendor–vendee relations."},
{t:"Quality control",s:"Block 5",q:"The fishbone or cause-and-effect diagram was developed in 1943 by",o:["Deming","Juran","Ishikawa","Pareto"],a:2,
 w:"It investigates and analyses systematically all the potential or real causes producing a single effect."},
{t:"Quality control",s:"Block 5",q:"Pareto analysis is described as a special type of",o:["control chart","histogram","scatter diagram","flowchart"],a:1,
 w:"It is applied to find and prioritise quality problems, conditions or their causes."},
{t:"SPC",s:"Block 5",q:"Statistical process control is defined as",o:["the use of statistical techniques to control the process or production method","the inspection of every finished unit","the auditing of financial records","the scheduling of production runs"],a:0,
 w:"Statistical Quality Control is often used interchangeably, and works by eliminating unusual variation in the process analysed."},
{t:"SPC",s:"Block 5",q:"Variation caused by factors inherent to the process (the materials, the equipment, the environment, natural human variation) is",o:["special cause variation","common cause variation","assignable variation","sporadic variation"],a:1,
 w:"It is impossible to eliminate; the aim is to keep it within acceptable limits. Special cause variation comes from a specific identifiable event and is usually easier to remove."},
{t:"SPC",s:"Block 5",q:"A single machine malfunctioning and producing specific defects is an example of",o:["common cause variation","special cause variation","measurement error","process capability"],a:1,
 w:"Contrast a poorly designed workstation that keeps every worker below full potential: that is inherent to the process, so common cause."},
{t:"SPC · Control charts",s:"Block 5",q:"The formula for the $\\bar{X}$ chart limits based on the population standard deviation is",o:["$\\bar{X} \\pm 3\\sigma$","$\\bar{X} \\pm A_2\\bar{R}$","$D_4\\bar{R}$ and $D_3\\bar{R}$","$\\bar{X} \\pm 2\\bar{R}$"],a:0,
 w:"Where the range is used instead, the limits become $\\bar{\\bar{X}} \\pm A_2\\bar{R}$; where only the range is charted, $\\mathrm{UCL} = D_4\\bar{R}$ and $\\mathrm{LCL} = D_3\\bar{R}$.",
 calc:"\\bar{X}\\text{ chart:}\\quad \\bar{X} \\pm 3\\sigma \\qquad \\text{with range:}\\quad \\bar{\\bar{X}} \\pm A_2\\bar{R}"},
{t:"SPC · Control charts",s:"Block 5",q:"Batch sample sizes are 10, 8, 12, 9, 15, 11 and 10. What is the centre line of the $\\bar{X}$ chart?",o:["10.71","11.00","9.50","12.14"],a:0,
 w:"$\\bar{X} = \\frac{10+8+12+9+15+11+10}{7} = \\frac{75}{7} = 10.71$.",
 calc:"\\bar{X} = \\frac{75}{7} = 10.71"},
{t:"SPC · Control charts",s:"Block 5",q:"For that same data the standard deviation is 2.12. What are the upper and lower control limits?",o:["17.07 and 4.35","12.83 and 8.59","15.00 and 6.00","13.00 and 8.00"],a:0,
 w:"$\\mathrm{UCL} = 10.71 + 3(2.12) = 17.07$ and $\\mathrm{LCL} = 10.71 − 3(2.12) = 4.35$.",
 calc:"\\bar{X} \\pm 3\\sigma = 10.71 \\pm 6.36 \\to 17.07 \\text{ and } 4.35"},
{t:"SPC · Control charts",s:"Block 5",q:"With $\\Sigma\\bar{X} = 76$ and $\\Sigma R = 26$ over 10 samples, and $A_2 = 0.58$, the limits of the range chart with mean are",o:["9.108 and 6.092","5.486 and 0","10.20 and 5.00","8.60 and 6.60"],a:0,
 w:"$\\bar{\\bar{X}} = \\frac{76}{10} = 7.6$ and $\\bar{R} = \\frac{26}{10} = 2.6$. The limits are $7.6 \\pm 0.58(2.6) = 9.108$ and $6.092$.",
 calc:"\\bar{\\bar{X}} \\pm A_2\\bar{R} = 7.6 \\pm 0.58(2.6) \\to 9.108 \\text{ and } 6.092"},
{t:"SPC · Control charts",s:"Block 5",q:"Using the same $\\bar{R} = 2.6$ with $D_4 = 2.11$ and $D_3 = 0$, the range chart without mean gives",o:["UCL 5.486 and LCL 0","UCL 9.108 and LCL 6.092","UCL 2.60 and LCL 0","UCL 2.11 and LCL 0.58"],a:0,
 w:"$\\mathrm{UCL} = D_4\\bar{R} = 2.11 \\times 2.6 = 5.486$ and $\\mathrm{LCL} = D_3\\bar{R} = 0 \\times 2.6 = 0$.",
 calc:"\\mathrm{UCL} = D_4\\bar{R} = 5.486 \\qquad \\mathrm{LCL} = D_3\\bar{R} = 0"},
{t:"SPC · Control charts",s:"Block 6",q:"Twenty-five components are sampled daily, averaging 4 mm with a standard deviation of 0.5 mm. What is the upper control limit?",o:["4.30","5.50","4.06","4.15"],a:0,
 w:"$\\mathrm{UCL} = \\bar{X} + 3\\left(\\frac{\\sigma}{\\sqrt{n}}\\right) = 4 + 3\\left(\\frac{0.5}{5}\\right) = 4 + 0.30 = 4.30$.",
 calc:"\\mathrm{UCL} = 4 + 3\\left(\\frac{0.5}{\\sqrt{25}}\\right) = 4 + 0.30 = 4.30"},
{t:"Quality control",s:"Block 5",q:"Which is NOT a listed benefit of quality control?",o:["Improving the quality of products and services","Reducing manufacturing and corporate costs","Reducing customer prices","Increasing the number of inspectors employed","Assuring on-time deliveries and availability"],a:3,
 w:"Employing more inspectors is a cost, not a benefit, and the whole thrust of QA is to prevent defects rather than inspect them out."},
/* ── 6 · PROJECT MANAGEMENT ── */
{t:"Project management",s:"Block 6 · Isaac",q:"A project is best defined as",o:["any activity carried out by an organisation","an undertaking involving a sequence of tasks completed within a specific period to attain a certain outcome","the routine operation of a production line","a department within an organisation"],a:1,
 w:"Building a road, an aircraft or a new cancer drug are the examples given. Projects differ from routine operations."},
{t:"Project management",s:"Block 6",q:"Rebuilding a factory destroyed by fire, to meet regulatory requirements, is which class of project?",o:["Compliance or emergency project","Operational project","Strategic project","Research project"],a:0,
 w:"They are the ‘must-do’ projects and attract penalties if not implemented. Operational projects support current operations (a TQM project); strategic projects support the long-run mission (new products, R&D)."},
{t:"Project management",s:"Block 6",q:"The five phases of the project life cycle are",o:["planning, scheduling, controlling, evaluating, closing","initiation, planning, execution, monitoring and control, close-out","appraisal, design, build, test, deliver","define, measure, analyse, improve, control"],a:1,
 w:"The last option is DMAIC (Six Sigma) and the first is the three stages of project management with extras attached. Keep the two lists apart."},
{t:"Project management",s:"Block 6",q:"The phase crucial in determining whether the project is viable, where scope, objectives and deliverables are defined, is",o:["initiation","planning","execution","close-out"],a:0,
 w:"Its activities include the kick-off meeting, identifying the project team, developing resources and getting infrastructure in place."},
{t:"Project management",s:"Block 6",q:"Archiving documents, turning over project results to clients and closing offices belongs to which phase?",o:["monitoring and control","execution","close-out","initiation"],a:2,
 w:"Close-out is the fifth and final phase. Monitoring and control, the fourth, runs alongside execution to keep the project on track and take corrective action where issues arise."},
{t:"Project management",s:"Block 6",q:"The three stages of project management are",o:["planning, scheduling and controlling","initiation, execution and closure","appraisal, evaluation and control","design, build and operate"],a:0,
 w:"Distinguish these three stages from the five phases of the project life cycle."},
{t:"Project management",s:"Block 6",q:"Which is NOT a step in project planning?",o:["Set up the objectives of the project","List the tasks, developing a work breakdown structure","Develop a network diagram","Estimate the cost and weeks associated with the project","Develop a budget for the resources"],a:2,
 w:"The network diagram belongs to project scheduling, along with identifying critical tasks and specifying the interrelationship of activities."},
{t:"Project management",s:"Block 6",q:"The key difference between a work breakdown structure and a Gantt chart is that",o:["the WBS may not contain timelines for specific activities but the Gantt chart does","the Gantt chart lists costs and the WBS does not","the WBS is used only for compliance projects","they are the same document under different names"],a:0,
 w:"The notes flag this point specifically. The WBS decomposes the work; the Gantt chart places it in time."},
{t:"Project management",s:"Block 6",q:"Which is NOT among the nine components of project management?",o:["Project scope","Contract requirement","Deliverables","Marketing plan","Risk and problem analysis"],a:3,
 w:"The nine are objectives, scope, contract requirement, schedules, resources, personnel, control, deliverables, and risk and problem analysis."},
{t:"Project management",s:"Block 6",q:"A project scope",o:["lists the names of the project team only","defines the boundary of the project: the tasks, goals, deliverables, costs and deadlines","fixes the discount rate for evaluation","is prepared only after close-out"],a:1,
 w:"It may also include justification for the project and what constitutes project success."},
{t:"Project evaluation",s:"Block 6",q:"Project evaluation is defined as",o:["the systematic assessment of the performance, effectiveness and outcome of a project against predetermined objectives","the process of scheduling activities","the calculation of the work breakdown structure","the recruitment of project staff"],a:0,
 w:"It compares baseline data (the benchmark stated in the objectives) with endline data, and runs across the project’s whole life span."},
{t:"Project evaluation",s:"Block 6",q:"Which method of project evaluation is described as the simplest and most widely used, and is applied to projects involving high uncertainty?",o:["Payback period","Net present value","Internal rate of return","Profitability index"],a:0,
 w:"Its major limitation is that it ignores the time value of money and profitability, though it does emphasise cash flows. Shorter paybacks are desirable."},
{t:"Project evaluation",s:"Block 6",q:"A project needs ₦40,000 as initial investment and generates ₦10,000 annually for 10 years. What is the payback period?",o:["4 years","2.5 years","10 years","0.25 years"],a:0,
 w:"$\\mathrm{PBP} = \\frac{\\text{initial investment}}{\\text{annual cash flow}} = \\frac{40{,}000}{10{,}000} = 4$ years.",
 calc:"\\mathrm{PBP} = \\frac{40{,}000}{10{,}000} = 4\\text{ years}"},
{t:"Project evaluation",s:"Block 6",q:"Using the same figures, what is the accounting rate of return?",o:["25%","40%","4%","10%"],a:0,
 w:"$\\mathrm{ARR} = \\frac{\\text{annual cash flow}}{\\text{initial investment}} = \\frac{10{,}000}{40{,}000} = 0.25 = 25\\%$.",
 calc:"\\mathrm{ARR} = \\frac{10{,}000}{40{,}000} = 25\\%"},
{t:"Project evaluation",s:"Block 6",q:"For a single project, the ARR decision rule is to",o:["accept if the calculated ARR is higher than the company target","accept if the ARR is positive","accept if the ARR is lower than the cost of capital","reject unless the ARR exceeds 50%"],a:0,
 w:"Where two projects compete, accept the one with the highest ARR provided it beats the company or industry target."},
{t:"Project evaluation",s:"Block 6",q:"The NPV decision rule is",o:["accept if $\\mathrm{NPV} > 0$, reject if $\\mathrm{NPV} < 0$, and decide on other factors if $\\mathrm{NPV} = 0$","accept if $\\mathrm{NPV} < 0$","accept only if $\\mathrm{NPV} = 0$","reject all projects with positive NPV"],a:0,
 w:"For mutually exclusive projects, accept the one with the highest positive NPV."},
{t:"Project evaluation",s:"Block 6",q:"₦40,000 is invested in an IT project at a cost of capital of 8%, and the discounted inflows total ₦408,960. What is the NPV?",o:["₦368,960","₦448,960","₦408,960","₦40,000"],a:0,
 w:"$\\mathrm{NPV} = \\text{PV of inflows} − \\text{initial investment} = 408{,}960 − 40{,}000 = ₦368{,}960$. The NPV being strongly positive, the project is accepted.",
 calc:"\\mathrm{NPV} = 408{,}960 − 40{,}000 = ₦368{,}960"},
{t:"Project evaluation",s:"Block 6",q:"The present value of a future sum is given by",o:["$\\mathrm{PV} = \\mathrm{FV}(1 + r)^n$","$\\mathrm{PV} = \\frac{\\mathrm{FV}}{(1 + r)^n}$","$\\mathrm{PV} = \\mathrm{FV} \\times n \\times r$","$\\mathrm{PV} = \\mathrm{FV} − r$"],a:1,
 w:"Which is the same as $\\mathrm{FV}(1 + r)^{−n}$. The inverse relation, $\\mathrm{FV} = \\mathrm{PV}(1 + r)^n$, compounds forward.",
 calc:"\\mathrm{PV} = \\frac{\\mathrm{FV}}{(1+r)^n} = \\mathrm{FV}(1+r)^{−n}"},
{t:"Project evaluation",s:"Block 6",q:"The internal rate of return is the discount rate at which",o:["the payback period equals zero","the NPV of the project is zero","the ARR equals the cost of capital","total cost is minimised"],a:1,
 w:"Accept a single project if the IRR exceeds the company’s cost of capital; between mutually exclusive projects, take the highest IRR that still clears the cost of capital."},
{t:"Project appraisal",s:"Block 6",q:"Which appraisal examines demand projections, marketing infrastructure, pricing, channels of distribution and the threat of substitutes?",o:["Market appraisal","Technical appraisal","Economic appraisal","Managerial appraisal"],a:0,
 w:"Technical appraisal looks at raw materials, equipment, power, transport and skilled manpower; economic appraisal at contribution to sectoral and social development and employment."},
{t:"Project appraisal",s:"Block 6",q:"Which appraisal uses profitability index, cost-benefit analysis, cash flow, NPV and IRR?",o:["Market appraisal","Financial appraisal","Environmental appraisal","Technical appraisal"],a:1,
 w:"It examines whether the financial costs and returns are properly estimated and whether the project is financially viable."},
{t:"Project appraisal",s:"Block 6",q:"Assessing impact on land use, commitment of natural resources, water, air, sound and geographical location is",o:["technical appraisal","managerial appraisal","environmental appraisal","market appraisal"],a:2,
 w:"Managerial appraisal focuses instead on promoters, organisation structure, managerial personnel and HR management."},
{t:"Project control",s:"Block 6",q:"The baseline plan is derived from",o:["the cost and duration information in the WBS database and the time-sequence data from network and resource scheduling","the customer’s marketing brief","the annual financial statements","the appraisal report alone"],a:0,
 w:"The baseline provides the elements against which performance is measured."},
{t:"Project control",s:"Block 6",q:"Earned value (EV) is defined as",o:["the market value of the finished project","the budgeted cost of the work performed","the actual cost of all work scheduled","the profit margin on the contract"],a:1,
 w:"It gives a realistic estimate of performance against a time-phased budget, measuring what you got for what you spent, not merely what you spent."},
{t:"Project control",s:"Block 6",q:"For a project expected to run five years, the reporting period might reasonably be",o:["a day","a week","a month","a year"],a:2,
 w:"The shorter the reporting period, the earlier problems are caught: a project lasting a month might report daily. The general guidance is one to four weeks."},
{t:"Project control",s:"Block 6",q:"During each reporting period, which two kinds of information must be collected?",o:["Data on actual performance, and information on changes to scope, schedule and budget","Marketing data and competitor data","Staff appraisals and training records","Tax returns and audited accounts"],a:0,
 w:"Actual performance covers the actual start and finish times of activities and the costs expended and committed."},
{t:"Project control",s:"Block 6",q:"Once changes are incorporated into the plan and agreed with the customer,",o:["the original baseline continues to apply","a new baseline plan must be established","the project must be terminated","control reporting stops"],a:1,
 w:"The scope, schedule and budget of the new baseline may all differ from the original; otherwise performance is being measured against a plan nobody is following."},
{t:"Project management",s:"Block 6",q:"Which is NOT listed among the objectives of project management?",o:["To determine the cost and duration of the project","To determine the level of resources needed","To maximise the market share of the organisation","To assist in allocating work and monitoring progress","To reduce or eliminate associated risk"],a:2,
 w:"Increasing revenue or market share is the aim of a strategic project, not an objective of project management as a discipline."}
]};
